version: '2'
services:
  vault:
    image: vault
    ports:
      - $PORT:8200
    environment:
      - VAULT_DEV_ROOT_TOKEN_ID=ichanhazcheezburger
      - VAULT_DEV_LISTEN_ADDRESS=0.0.0.0:8200
      - VAULT_API_ADDR=http://localhost:$PORT
    command:
      - vault
      - server
      - -dev
